def City():
    screen_info = pygame.display.Info()  
    screen_width = 1366
    screen_height = 768
    screen = pygame.display.set_mode((screen_width, screen_height))


    GRIJS = (79, 79, 79)
    LICHTGRIJS = (121, 121, 121)
    BRUIN = (82, 59, 32)
    screen.fill(LICHTGRIJS)
    pygame.draw.rect(screen, BRUIN, (0, 350, 1366, 50))
    pygame.draw.rect(screen, BRUIN, (0, 425, 1366, 50))
    pygame.draw.rect(screen, GRIJS, (230, 64, 900, 100)) #BREEDTE, HOOGTE, LENGTE, BREEDTE
    pygame.draw.circle(screen, GRIJS, (1130, 164), 100, width=0, draw_top_right=True, draw_top_left=False, draw_bottom_left=True, draw_bottom_right=False)
    pygame.draw.rect(screen, GRIJS, (1130, 164, 100, 442))
    pygame.draw.circle(screen, LICHTGRIJS, (1130, 164), 20, width=0, draw_top_right=True, draw_top_left=True, draw_bottom_left=True, draw_bottom_right=True)
    pygame.draw.circle(screen, GRIJS, (1130, 606), 100, width=0, draw_top_right=False, draw_top_left=False, draw_bottom_left=False, draw_bottom_right=True)
    pygame.draw.rect(screen, GRIJS, (980, 606, 150, 100))
    pygame.draw.rect(screen, GRIJS, (380, 556, 600, 200))
    Schuin_1 = pygame.Surface((400, 50), pygame.SRCALPHA)
    Schuin_1.fill((LICHTGRIJS), rect=None, special_flags=0)
    Schuin_1_Schuin= pygame.transform.rotate(Schuin_1, 10)
    screen.blit(Schuin_1_Schuin,(372, 487))
    Schuin_1 = pygame.Surface((400, 50), pygame.SRCALPHA)
    Schuin_1.fill((LICHTGRIJS), rect=None, special_flags=0)
    Schuin_1_Schuin= pygame.transform.rotate(Schuin_1, 350)
    screen.blit(Schuin_1_Schuin,(372, 707))
    Schuin_1 = pygame.Surface((400, 50), pygame.SRCALPHA)
    Schuin_1.fill((LICHTGRIJS), rect=None, special_flags=0)
    Schuin_1_Schuin= pygame.transform.rotate(Schuin_1, -10)
    screen.blit(Schuin_1_Schuin,(586, 487))
    Schuin_1 = pygame.Surface((400, 50), pygame.SRCALPHA)
    Schuin_1.fill((LICHTGRIJS), rect=None, special_flags=0)
    Schuin_1_Schuin= pygame.transform.rotate(Schuin_1, -350)
    screen.blit(Schuin_1_Schuin,(586, 707))
    Schuin_1 = pygame.Surface((40, 40), pygame.SRCALPHA)
    Schuin_1.fill((LICHTGRIJS), rect=None, special_flags=0)
    Schuin_1_Schuin= pygame.transform.rotate(Schuin_1, 45)
    screen.blit(Schuin_1_Schuin,(788, 629))
    Schuin_1 = pygame.Surface((40, 40), pygame.SRCALPHA)
    Schuin_1.fill((LICHTGRIJS), rect=None, special_flags=0)
    Schuin_1_Schuin= pygame.transform.rotate(Schuin_1, 45)
    screen.blit(Schuin_1_Schuin,(511, 629))
    pygame.draw.rect(screen, LICHTGRIJS, (540, 630, 275, 55))
    pygame.draw.rect(screen, GRIJS, (230, 606, 150, 100))
    pygame.draw.circle(screen, GRIJS, (230, 606), 100, width=0, draw_top_right=False, draw_top_left=False, draw_bottom_left=True, draw_bottom_right=False)
    pygame.draw.rect(screen, GRIJS, (130, 164, 100, 442))
    pygame.draw.circle(screen, GRIJS, (180, 250), 100, width=0, draw_top_right=True, draw_top_left=True, draw_bottom_left=True, draw_bottom_right=True)
    pygame.draw.circle(screen, LICHTGRIJS, (180, 250), 20, width=0, draw_top_right=True, draw_top_left=True, draw_bottom_left=True, draw_bottom_right=True)
    pygame.draw.circle(screen, GRIJS, (230, 164), 100, width=0, draw_top_right=False, draw_top_left=True, draw_bottom_left=False, draw_bottom_right=False)
    
    pygame.display.update()
